[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd app/backend && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd app/backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
